- name: Create file using variables
  hosts: localhost
  connection: local
  vars:
   - miip: "1.2.3.4"
   - milista: ["apache2","mariadb","php5"]
   - milista_larga:
       - apache2
       - mariadb
       - php5
   - midic: {web: "apache2", bd: "mariadb", script: "php5"}
   - midic_long:
       - web: apache2
       - bd: mariadb
       - script: php5 
   - mitexto: |
       primera linea
       segunda linea
       tercera linea
   - milinealarga: >
       inicio linea
       continuacion linea
       final linea

  tasks: 
    - name: Crear archivo hosts
      template: src=hosts.j2 dest=/tmp/hosts owner=root group=root mode=0644
    - name: crear archivo hosts yaml
      template:
        src: hosts.j2
        dest: /tmp/hosts
        owner: root
        group: root
        mode: 0644
